### ISSUE TITLE
idea for improvement

### ISSUE THREAD

**Issue by ve3sjk** [carlosgs/Cyclone-PCB-Factory#31]
Looking at the smooth rod holders seem to me like extra parts in a way. Would it not be easier to make the holes for the x smooth rods full holes and incorporate some captive nuts going into the frame to hold them. something like the way the drive gears are held onto the motors. It would eliminate all the smooth rod holders, half the hardware, and possibly make things squarer. I find the pressure and how evenly you tighten the holders done, effects the squareness of the rods based on how good the half circle printed in the holders themselves.

 Just thinking out loud on this one,

**Comment by carlosgs** [comment]
I think it makes sense to reduce hardware, but having "open" holders simplifies the assembly process quite a lot!
