### ISSUE TITLE
endstop holders

### ISSUE THREAD

**Issue by ve3sjk** [carlosgs/Cyclone-PCB-Factory#34]
I have modified my files a bit to allow for different end stop configurations, so far i moved the end stop out of the standard parts lib, added as a separate scad file and included it in the main scad file. I moved the parameters for it to the configuration files and added if statements to suppress it in the x-frames files. I have this machine setup to offset the x axis to the middle so i am running an offset of -180 instead of -80 for that setting. I am working off a base files that are v2.1.

Everything is working except for this behavior, not sure where in the code i need to make changes to stop it.

the left frame without with end stop

![leftframenoendstop](https://cloud.githubusercontent.com/assets/7632604/5389433/28408f90-80ca-11e4-8b80-ad10e5648f79.png)

and with it turned on

![leftframe](https://cloud.githubusercontent.com/assets/7632604/5389435/2cabfede-80ca-11e4-8b9c-7461b35f7091.png)

the right frames printed good, but i guess you could say the same for motor mount structure as well it just continues to the end of the frame although it doesn't bother me at all.

![2014-12-10 23 54 23](https://cloud.githubusercontent.com/assets/7632604/5389459/8f52c3e2-80ca-11e4-890f-720cb23b889c.jpg)
![2014-12-10 23 54 10](https://cloud.githubusercontent.com/assets/7632604/5389460/917d1212-80ca-11e4-8bc4-b0904434c245.jpg)

**Comment by carlosgs** [comment]
Fixed with Cyclone XL <https://github.com/carlosgs/Cyclone-PCB-Factory/tree/master/Output_files/Cyclone_XL> :-)
