### ISSUE TITLE
Como hacer milling con Fritzing

### ISSUE THREAD

**Issue by b4zz4** [carlosgs/Cyclone-PCB-Factory#47]
Tengo una cyclone-pcb desde hace unos meses y quería hacer un circuito usando fritzing por que el resto de los programas me resultan complicado y no los uso muy bien, ¿existe algún tutorial de como hacer esto?

saludos

**Comment by carlosgs** [comment]
Hola, pregúntalo en el foro español (https://groups.google.com/forum/#!forum/cyclone-pcb-factory-es ) o inglés (https://groups.google.com/forum/#!forum/cyclone-pcb-factory ).

No he usado Frizting pero imagino que puede exportar como Gerber; una vez tengas los ficheros Gerber, puedes usar el programa FlatCam (http://flatcam.org/manual/index.html ) para generar los Gcode.
Saludos,
Carlos
