### ISSUE TITLE
XY gear cover

### ISSUE THREAD

**Issue by PaulusJB** [carlosgs/Cyclone-PCB-Factory#48]
Hi,
I'm having a bit trouble with "Cycl_XYgearCover_x2.stl", even with "Cycl_tapaEngranajesXY.stl" which remains as the same file; stl's broken!
any possibility of reuploading a new export?

**Comment by carlosgs** [comment]
Hi Paulus, which software are you opening them with? They work fine with Cura. May I suggest opening them with Cura and saving into a new STL file?

**Comment by PaulusJB** [comment]
I was trying to make a .gcode using slic3r, and for some reason it shows it broken-like. Using Cura was the solution!

**Comment by carlosgs** [comment]
Awesome, thanks for getting back to confirm it! :D
