### ISSUE TITLE
consulta sobre engranajes

### ISSUE THREAD

**Issue by b4zz4** [carlosgs/Cyclone-PCB-Factory#50]
¿probaron usar engranajes estilo [Herringbone](http://reprap.org/wiki/Herringbone_Extruder_Driver) ?

**Comment by carlosgs** [comment]
Hola! Sí, la primera versión usaba ese tipo de engranajes:  
<https://github.com/carlosgs/Cyclone-PCB-Factory/releases/tag/v0.9.7>

Al final decidí cambiarlos por engranajes normales debido a que si no se imprimen perfectamente, la estructura Herringbone "baila" un poco y transmite esa vibración en forma de movimientos axiales (es decir, hace oscilar la varilla roscada longitudinalmente).  
Con engranajes normales, sigue siendo posible una cierta oscilación, pero ésta queda desacoplada.  

Si te preocupa el backlash entre los dientes de los engranajes, piensa que la reducción con la varilla roscada es muy grande y minimiza dicho efecto.  

Saludos,
Carlos
