### ISSUE TITLE
Which parameters should I use to print the parts?

### ISSUE THREAD

**Issue by gsalvati** [CarlosGS/Cyclone-PCB-Factory#56]
**Which parameters should I use to print the parts?**
I found only this:
https://github.com/CarlosGS/Cyclone-PCB-Factory/tree/v2.3/Output_files/STL_plates

Can I use this configuration to print all the parts?

**Comment by CarlosGS** [comment]
Indeed! Some people have reported that holes are too large when printing at very fine resolution, so in fact it is better to use the coarse settings

Maybe I'd raise a little bit the fill density, to 25%
Please let me know of any issues while printing the parts

**Comment by gsalvati** [comment]
Thanks a lot
