### ISSUE TITLE
Nema 17 - Specify load

### ISSUE THREAD

**Issue by gsalvati** [CarlosGS/Cyclone-PCB-Factory#58]
Can you specify the NEMA 17 stepper motor load / kind on wiki ( Bill of materials )?

**Comment by CarlosGS** [comment]
Hi, I have just added it as: "NEMA 17 motor. 1.8 deg, 4.8 kg/cm (or similar)"
Cheers!

**Comment by gsalvati** [comment]
Thanks a lot!

**Comment by gsalvati** [comment]
On all 3 motors? can I use one with 1.1kg/mm on Z axis?

**Comment by CarlosGS** [comment]
Yeah it sounds like it would work. Haven't tried it though.
