### ISSUE TITLE
fresas

### ISSUE THREAD

**Issue by b4zz4** [CarlosGS/Cyclone-PCB-Factory#65]
que tamaño y modelo de fresas usan normalmente para pcb, yo usaba una v1001 pero ahora me esta andando muy malo, nunca andubo demaciado bien la cnc :S

**Comment by CarlosGS** [comment]
Hola, [en este link](https://github.com/CarlosGS/Cyclone-PCB-Factory/wiki/List-of-suppliers#consumables) puedes encontrar la lista de herramientas que utilizo, junto a los links de compra en eBay.

Para este tipo de cuestiones te ruego que uses [el foro de Google Groups](https://groups.google.com/group/cyclone-pcb-factory-es).

Un saludo!
