### ISSUE TITLE
bill of materials in spanish

### ISSUE THREAD

**Issue by jbrereton6** [CarlosGS/Cyclone-PCB-Factory#68]
the bill of materials is in Spanish

**Comment by falconxperto** [comment]
maybe u can translate that... xd

**Comment by jbrereton6** [comment]
one of the words translates into asparagus

**Comment by CarlosGS** [comment]
This made my day :-)
I've translated the page to english language: https://github.com/CarlosGS/Cyclone-PCB-Factory/wiki/Shopping-list

_Espárrago does mean Asparagus ;) In this context, it means grub screw!_

Sorry for the delay and thanks for the feedback. I hope the translation helps!
