### ISSUE TITLE
Editable Drawing Files

### ISSUE THREAD

**Issue by FelipeBezFontana** [CarlosGS/Cyclone-PCB-Factory#71]
Hi,

I'm thinking of building a Cyclone with some changes in mechanicals parts. Can anybody send me the drawings in *.SLDPRT format?

Thank You!

**Comment by CarlosGS** [comment]
Sorry, I don't know that format. I hope someone else can help!

**Comment by FelipeBezFontana** [comment]
This format is from SolidWorks. Do you have any other format editable by SolidWorks or other program?

**Comment by CarlosGS** [comment]
The machine is designed with OpenScad, all of the .scad sources are available. I don't think SolidWorks can import this format yet :(

**Comment by FelipeBezFontana** [comment]
Sure, I get it. Thanks for the help and congratulations for the great work! :)

**Comment by CarlosGS** [comment]
There are also Step files, maybe those are better for editing rather than the STLs
https://github.com/CarlosGS/Cyclone-PCB-Factory/tree/master/bq_additions/Production/STEP

**Comment by FelipeBezFontana** [comment]
Hi, I tried to edit the *.stp file in SolidWorks today and I had a good result. Thanks for helping me. ;)

**Comment by CarlosGS** [comment]
That's awesome!! I hope you can modify it to fit your needs
