### ISSUE TITLE
BoM redirects to Wiki main page

### ISSUE THREAD

**Issue by brnl** [CarlosGS/Cyclone-PCB-Factory#74]
Hi,

I'm curious if this project is still alive. I'm trying to research how feasible it is to build the Cyclone 2 but the (**English**) documentation seems outdated.

One problem is the BoM (https://github.com/carlosgs/Cyclone-PCB-Factory/wiki/Bill-of-materials) redirects back to the Wiki main page (https://github.com/carlosgs/Cyclone-PCB-Factory/wiki)

Also, the [suppliers page](https://github.com/carlosgs/Cyclone-PCB-Factory/wiki/List-of-suppliers) contains only dead links.

Is the project still supported or am I better off buying a ready-made kit?

Thanks for your time!

**Comment by CarlosGS** [comment]
Hi! I've fixed the link to the BoM in the main wiki page.
However, I think you are right: nowadays it is better (and cheaper) to purchase a generic CNC kit.
Cheers,
Carlos

**Comment by brnl** [comment]
Hi @CarlosGS,

Thank you for your honest reply. I love your work, though. Was an awesome initiative!

Cheers,
Bram

**Comment by CarlosGS** [comment]
Thanks, and happy milling! :-)
