### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by moliata** [CarlosGS/Cyclone-PCB-Factory#80]
Hello,
what should be the optimal height for the work base (as well as main)? At the moment, I am able to purchase PlexiGlass sheets with a height between 1-12mm (except 7mm and 9mm).
Best regards,
Ben.

**Comment by CarlosGS** [comment]
Hi, I would recommend using wood 15mm thick. It will be easier to machine and also to fix the working materials to the base.

Otherwise the thicker the better since it will be less sensitive to vibrations.

**Comment by moliata** [comment]
@CarlosGS thank you! I will be using wood for the main base, but PlexiGlass for the work base. How thick should the work base be.

**Comment by Helicon007** [comment]
Hi Ben, 

I use a 12mm plexi/acryl plate as base, does the job quiet well. 

Regards, Helicon

**Comment by moliata** [comment]
Isn't that too thick for the work base (milling area)?

**Comment by moliata** [comment]
@CarlosGS regarding vibrations, I will be using 4pcs Rubber Feet from Adafruit, so the base won't be touching the table itself.

**Comment by CarlosGS** [comment]
Good idea!

**Comment by moliata** [comment]
@CarlosGS in any case, I should still go with a 15mm thick wood base, if I'm using rubber feet? Also, 12mm thick PlexiGlass for the work base (milling area)? I'm in particular looking at having the same thickness main and work as BQ's Cyclone PCB Factory. Lastly, for the "wire management tube", I am looking at a braided sleeves for cables, what size should they be to fit everything in?

**Comment by CarlosGS** [comment]
Sorry, I don't remember the exact diameter and don't have the machine at hand to measure it :(

**Comment by moliata** [comment]
@CarlosGS when you will have the machine somewhere around, please send the diameter over here, thanks!

**Comment by CarlosGS** [comment]
I see my version is not exactly the one from bq, for instance it has a different cable management tube. In my case it is a ~15mm acrylic pipe recycled from some other project.

**Comment by moliata** [comment]
Thank you anyways! It seems, it's a 4mm wire management tube.

**Comment by CarlosGS** [comment]
Please use the Cyclone Google groups forum for questions, instead of GitHub
issues

**Comment by moliata** [comment]
@CarlosGS sorry! It doesn't seem to be active, so I made issues
