### ISSUE TITLE
Mega3D Spacer (Y axis, step 12d)

### ISSUE THREAD

**Issue by moliata** [CarlosGS/Cyclone-PCB-Factory#82]
Hello,
where can I find the DXF file for acrylic spacer (Y axis, step 12d) used for the Mega3D Board?
Best regards,
Ben.
P.S: @CarlosGS don't you have a file somewhere around? I really need it! Maybe BQ has them, if so, I could send them an email...

**Comment by CarlosGS** [comment]
Hi, it should have been here: https://github.com/bq/Cyclone-PCB-Factory/tree/master/bq_additions/Proto/CAD
But they did not upload that particular dxf, probably difficult to get it back from them.

**Comment by moliata** [comment]
@CarlosGS do you have the acrylic part yourself (not the file, but the actual part)?

**Comment by CarlosGS** [comment]
Nope, in my machine the board is screwed to the base directly. I believe it was designed by @PedroDeOro, maybe he still has the original dxf :-)

**Comment by moliata** [comment]
@CarlosGS thanks, I sent an email to Pedro, if he shares it with me, I'll post a PR, thanks!

**Comment by moliata** [comment]
@CarlosGS doesn't seem he is going to respond any time soon.
